




















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ManHouse`
//     Provider:               `System.Data.SQLite`
//     Connection String:      `Data Source=C:\MiCarpeta\PUNTONET\HOMEVISUAL\GitHub\APIServiceStack2014\BD\ManHouse.sqlite`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SQLiteFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace ManHouse
{
}
#pragma warning restore 1591
