// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace APIServiceStack2014.POCO
{
	[Alias("Products")]
    public partial class Product : IHasId<long> 
    {
        [Alias("Id")]
        public long? Id { get; set;}
        [StringLength(8000)]
        public string ProductName { get; set;}
        [Required]
        public long SupplierId { get; set;}
        [Required]
        public long CategoryId { get; set;}
        [StringLength(8000)]
        public string QuantityPerUnit { get; set;}
        [Required]
        public decimal UnitPrice { get; set;}
        [Required]
        public long UnitsInStock { get; set;}
        [Required]
        public long UnitsOnOrder { get; set;}
        [Required]
        public long ReorderLevel { get; set;}
        [Required]
        public long Discontinued { get; set;}
        public DateTime? LastUpdated { get; set;}
    }
}
#pragma warning restore 1591
